//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeThi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BacSi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BacSi()
        {
            this.LichHen = new HashSet<LichHen>();
        }
        [Key]
        public int MaBS { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 5)]
        public string TenBS { get; set; }
        [Required]
        public string ChuyenKhoa { get; set; }
        [Required]
        [Range(0, int.MaxValue)]
        public Nullable<int> SoNamKN { get; set; }
        [Required]
        [RegularExpression("^\\d{10}$\r\n")]
        public string DienThoai { get; set; }
        public int TienKham
        {
            get
            {
                return SoNamKN >= 10 ? 500000 : 300000;
            }
        }
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichHen> LichHen { get; set; }
    }
}
