//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeThi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BenhNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BenhNhan()
        {
            this.LichHen = new HashSet<LichHen>();
        }

        [Key]
        public int MaBN { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 5)]
        public string HoTen { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Required]
        public Nullable<bool> GioiTinh { get; set; }
        [Required]
        [RegularExpression("^\\d{10}$\r\n")]
        public string DienThoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichHen> LichHen { get; set; }
    }
}
