//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeThi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class LichHen
    {
        [Key, Column(Order = 0)]
        public int MaLH { get; set; }
        [Key, Column(Order = 1)]
        [ForeignKey("BenhNhan")]
        public Nullable<int> MaBN { get; set; }
        [Key, Column(Order = 2)]
        [ForeignKey("BacSi")]
        public Nullable<int> MaBS { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayHen { get; set; }
        [Required]
        public string LyDo { get; set; }

        public virtual BacSi BacSi { get; set; }
        public virtual BenhNhan BenhNhan { get; set; }
    }
}
